"use client";

import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "el" | "it" | "hi";

export const languages: { code: Language; label: string; flag: string }[] = [
    { code: "en", label: "English", flag: "🇬🇧" },
    { code: "el", label: "Ελληνικά", flag: "🇬🇷" },
    { code: "it", label: "Italiano", flag: "🇮🇹" },
    { code: "hi", label: "हिन्दी", flag: "🇮🇳" },
];

export const translations: Record<Language, Record<string, string>> = {
    en: {
        // Nav
        nav_home: "Home",
        nav_menu: "Menu",
        nav_story: "Our Story",
        nav_contact: "Contact",
        nav_order: "Order",
        nav_est: "Est. MMXIX · Bengaluru",

        // Hero
        hero_badge: "✦  Fine Mediterranean Cuisine  ✦",
        hero_title: "WHERE ANCIENT",
        hero_subtitle: "flavours live on",
        hero_desc: "Born in the kitchens of the Aegean and refined under the Mediterranean sun — every plate at Agora is a living artefact of taste, fire, and tradition.",
        hero_divider: "— ✦ —",
        hero_cta1: "View Menu",
        hero_cta2: "Our Story",
        hero_stat1: "Guest Rating",
        hero_stat2: "Delivery",
        hero_stat3: "Min. Order",

        // Sections
        about_label: "Our Story",
        about_title1: "FROM THE AGORA",
        about_title2: "to your table",
        about_p1: "In ancient Greece, the Agora was more than a marketplace — it was where ideas, culture, and the finest harvests of the land converged. We carry that spirit forward.",
        about_p2: "Chef Nikos Papadopoulos trained in Athens and Napoli before bringing the fire-craft traditions of the Mediterranean to Bengaluru. Every recipe is a two-thousand-year conversation.",
        about_cta: "Explore Our Menu",
        about_img_tagline: "Serving ancient fire-craft",
        about_img_est: "Est. MMXIX",

        highlights_label: "The Agora Way",
        highlights_title: "Why Guests Return",
        highlights_subtitle: "Every detail is deliberate. Every ingredient chosen. Every flame tended with intention.",

        best_label: "Most Beloved",
        best_title: "Favoured by the Agora",
        best_link: "Full Menu",

        cta_eyebrow: "✦  ΚAΛΗ ΟΡΕΞΗ  ✦",
        cta_title: "READY TO FEAST?",
        cta_subtitle: "like the gods once did",
        cta_desc: "Order from our full menu and receive your meal in 25–35 minutes. Complimentary delivery on orders above ₹499.",
        cta_btn: "Order Now",

        // Menu page
        menu_eyebrow: "The Culinary Codex",
        menu_title: "OUR FULL MENU",
        menu_subtitle: "dishes, each a story forged by fire and tradition",
        codex_all: "All Dishes",
        sidebar_title: "The Codex",
        search_ph: "Search the codex…",
        filter_veg: "Vegetable",
        filter_best: "Beloved",
        no_dishes: "No dishes found",
        no_dishes_sub: "Try a different search",
        view_order: "View Order",

        // Cart
        cart_title: "Your Order",
        cart_from: "items from Agora",
        cart_empty: "Your cart is empty",
        cart_empty_sub: "Add some delicious items from our menu",
        cart_subtotal: "Subtotal",
        cart_delivery: "Delivery Fee",
        cart_taxes: "Taxes (5%)",
        cart_total: "Total",
        place_order: "Place Order",
        clear_cart: "Clear cart",
        order_placed: "Order Placed!",
        order_msg: "Your food is being prepared with love. 25–35 mins estimated delivery.",

        // Footer
        footer_tagline: "Born of the Aegean, refined under the Mediterranean sun. Agora brings ancient fire-craft to your table.",
        footer_nav: "Navigate",
        footer_menu_col: "The Menu",
        footer_find: "Find Us",
        footer_copy: "AGORA · BENGALURU · ALL RIGHTS RESERVED",
        footer_open: "11AM – 11:30PM daily",

        // Highlights content
        h1_title: "Open Fire Mastery",
        h1_desc: "Every dish is born of open flame. Our chefs train in the ancient art of fire — unlocking flavours no oven could dream of.",
        h2_title: "Mediterranean Harvest",
        h2_desc: "Cold-pressed olive oil, stone-ground spices, and heirloom grains sourced directly from Aegean farms.",
        h3_title: "Culinary Heritage",
        h3_desc: "Our recipes trace back generations — living stories of Greek, Italian, and Levantine kitchens, served with modern reverence.",
        h4_title: "30 Min or Less",
        h4_desc: "Hot, beautifully packaged, and cosseted all the way to your door. Time-honoured taste, modern speed.",

        // Categories
        cat_starters: "Starters",
        cat_mains: "Mains",
        cat_grills: "From the Grill",
        cat_breads: "Breads",
        cat_desserts: "Desserts",
        cat_drinks: "Drinks",

        // UI components
        add_btn: "ADD",
        bestseller: "Bestseller",

        // Items
        s1_name: "Agora Bruschetta",
        s1_desc: "Toasted sourdough with fire-roasted tomatoes, fresh basil, and aged balsamic drizzle",
        s2_name: "Mykonos Prawns",
        s2_desc: "Jumbo prawns marinated in lemon, garlic, and wild oregano, charred over open coals",
        s3_name: "Grilled Halloumi",
        s3_desc: "Cypriot goat's cheese grilled with honey, thyme, and toasted sesame seeds",
        s4_name: "Ionian Calamari",
        s4_desc: "Lightly battered squid rings with lemon-herb salt and smoked paprika aioli",
        m1_name: "Aeaean Lentil Stew",
        m1_desc: "Slow-cooked black lentils with aromatic roots, finished with a swirl of cold-pressed olive oil",
        m2_name: "Lemon Garlic Pollo",
        m2_desc: "Roasted chicken in a velvety lemon-butter sauce with capers and Mediterranean herbs",
        m3_name: "Herb-Crusted Lamb",
        m3_desc: "Tender lamb slow-cooked with rosemary, thyme, and a hint of red wine reduction",
        m4_name: "Florence Spinach Gnocchi",
        m4_desc: "Soft potato gnocchi with fresh spinach, ricotta, and a drizzle of sage butter",
        m5_name: "Adriatic Sea Bass",
        m5_desc: "Pan-seared sea bass with roasted cherry tomatoes, olives, and lemon zest",
        g1_name: "Olympian Mixed Grill",
        g1_desc: "A grand platter of lamb chops, herbed chicken, and bifteki with tzatziki",
        g2_name: "Portobello Al Forno",
        g2_desc: "Large mushrooms stuffed with garlic, herbs, and pecorino, roasted in the stone oven",
        g3_name: "Sicily Lamb Skewers",
        g3_desc: "Marinated lamb cubes with peppers and red onions, grilled over charcoal",
        b1_name: "Herb Focaccia",
        b1_desc: "Traditional Italian flatbread with sea salt, rosemary, and olive oil",
        b2_name: "Pita Artizana",
        b2_desc: "Soft, hand-stretched Greek pita bread, perfect for dipping",
        b3_name: "Tuscan Garlic Bread",
        b3_desc: "Thick slices of crusty bread rubbed with garlic and toasted with butter",
        d1_name: "Honey Baklava Brûlée",
        d1_desc: "Classic layered pastry with walnuts and honey, finished with a caramelized sugar top",
        d2_name: "Tiramisu Decadence",
        d2_desc: "Layers of coffee-soaked ladyfingers and whipped mascarpone with dark cocoa dust",
        d3_name: "Saffron Panna Cotta",
        d3_desc: "Silky Italian cream dessert infused with saffron and topped with crushed pistachios",
        dr1_name: "Aegean Nectar",
        dr1_desc: "Sparkling grape juice with hints of honey and elderflower",
        dr2_name: "Rosemary Lemonade",
        dr2_desc: "Freshly squeezed lemon with a sprig of garden rosemary and light agave",
        dr3_name: "Stone-Ground Espresso",
        dr3_desc: "Rich, dark roast coffee served with a small piece of dark chocolate",
    },

    el: {
        nav_home: "Αρχική",
        nav_menu: "Μενού",
        nav_story: "Η Ιστορία μας",
        nav_contact: "Επικοινωνία",
        nav_order: "Παραγγελία",
        nav_est: "Ιδρ. MMXIX · Μπενγκαλούρου",

        hero_badge: "✦  Αυθεντική Μεσογειακή Κουζίνα  ✦",
        hero_title: "ΕΚΕΙ ΟΠΟΥ ΟΙ ΑΡΧΑΙΕΣ",
        hero_subtitle: "γεύσεις ζουν ξανά",
        hero_desc: "Γεννημένη στις κουζίνες του Αιγαίου και τελειοποιημένη κάτω από τον μεσογειακό ήλιο — κάθε πιάτο στην Αγορά είναι ένα ζωντανό αντικείμενο γεύσης, φωτιάς και παράδοσης.",
        hero_divider: "— ✦ —",
        hero_cta1: "Το Μενού",
        hero_cta2: "Η Ιστορία μας",
        hero_stat1: "Βαθμολογία",
        hero_stat2: "Παράδοση",
        hero_stat3: "Ελάχ. Παραγγ.",

        about_label: "Η Ιστορία μας",
        about_title1: "ΑΠΟ ΤΗΝ ΑΓΟΡΑ",
        about_title2: "στο τραπέζι σου",
        about_p1: "Στην αρχαία Ελλάδα, η Αγορά ήταν πολύ περισσότερα από αγορά. Είναι όπου ιδέες, πολιτισμός, και οι καλύτερες συγκομιδές της γης ενώθηκαν. Συνεχίζουμε αυτό το πνεύμα.",
        about_p2: "Ο Σεφ Νίκος Παπαδόπουλος εκπαιδεύτηκε στην Αθήνα και τη Νάπολη πριν φέρει τις παραδόσεις της μεσογειακής φωτιάς στο Μπενγκαλούρου.",
        about_cta: "Εξερεύνησε το Μενού",
        about_img_tagline: "Υπηρετώντας την αρχαία τέχνη της φωτιάς",
        about_img_est: "Ιδρ. MMXIX",

        highlights_label: "Η Φιλοσοφία μας",
        highlights_title: "Γιατί Οι Φιλοξενούμενοι Επιστρέφουν",
        highlights_subtitle: "Κάθε λεπτομέρεια είναι σκόπιμη. Κάθε υλικό επιλεγμένο. Κάθε φλόγα φροντισμένη με πρόθεση.",

        best_label: "Αγαπημένα",
        best_title: "Επιλεγμένα από την Αγορά",
        best_link: "Πλήρες Μενού",

        cta_eyebrow: "✦  ΚΑΛΗ ΟΡΕΞΗ  ✦",
        cta_title: "ΕΤΟΙΜΟΣ ΝΑ ΔΕΙΠΝΗΣΕΙΣ;",
        cta_subtitle: "όπως οι θεοί κάποτε",
        cta_desc: "Παραγγείλτε από το πλήρες μενού μας και λάβετε το γεύμα σας σε 25–35 λεπτά.",
        cta_btn: "Παραγγελία τώρα",

        menu_eyebrow: "Ο Κώδικας Κουζίνας",
        menu_title: "ΤΟ ΠΛΗΡΕΣ ΜΕΝΟΥ ΜΑΣ",
        menu_subtitle: "πιάτα, καθένα μια ιστορία σφυρηλατημένη στη φωτιά",
        codex_all: "Όλα τα Πιάτα",
        sidebar_title: "Ο Κώδικας",
        search_ph: "Αναζήτηση…",
        filter_veg: "Χορτοφαγικό",
        filter_best: "Αγαπημένα",
        no_dishes: "Δεν βρέθηκαν πιάτα",
        no_dishes_sub: "Δοκιμάστε διαφορετική αναζήτηση",
        view_order: "Η Παραγγελία μου",

        cart_title: "Η Παραγγελία σου",
        cart_from: "πιάτα από την Αγορά",
        cart_empty: "Το καλάθι σου είναι άδειο",
        cart_empty_sub: "Πρόσθεσε νόστιμα πιάτα",
        cart_subtotal: "Υποσύνολο",
        cart_delivery: "Κόστος Αποστολής",
        cart_taxes: "Φόρος (5%)",
        cart_total: "Σύνολο",
        place_order: "Παραγγείλτε",
        clear_cart: "Εκκαθάριση",
        order_placed: "Η Παραγγελία Ελήφθη!",
        order_msg: "Το φαγητό σας ετοιμάζεται με αγάπη. Εκτιμώμενη παράδοση 25–35 λεπτά.",

        // Footer
        footer_tagline: "Γεννημένο στο Αιγαίο, τελειοποιημένο στη Μεσόγειο. Η Αγορά φέρνει την αρχαία τέχνη της φωτιάς στο τραπέζι σου.",
        footer_nav: "Πλοήγηση",
        footer_menu_col: "Το Μενού",
        footer_find: "Βρείτε μας",
        footer_copy: "ΑΓΟΡΑ · ΜΠΕΝΓΚΑΛΟΥΡΟΥ · ΜΕ ΕΠΙΦΥΛΑΞΗ ΠΑΝΤΟΣ ΔΙΚΑΙΩΜΑΤΟΣ",
        footer_open: "11ΠΜ – 11:30ΜΜ καθημερινά",

        h1_title: "Τέχνη της Φωτιάς",
        h1_desc: "Κάθε πιάτο γεννιέται από ανοιχτή φλόγα. Οι σεφ μας εξασκούνται στην αρχαία τέχνη της φωτιάς.",
        h2_title: "Μεσογειακή Συγκομιδή",
        h2_desc: "Ελαιόλαδο πρώτης εκχύλισης, μπαχαρικά αλεσμένα σε πέτρα, από Αιγαιοπελαγίτικες φάρμες.",
        h3_title: "Γαστρονομική Κληρονομιά",
        h3_desc: "Οι συνταγές μας ανάγονται σε γενεές — ζωντανές ιστορίες ελληνικών, ιταλικών κουζινών.",
        h4_title: "30 Λεπτά ή Λιγότερο",
        h4_desc: "Ζεστό, όμορφα συσκευασμένο φαγητό που φτάνει στην πόρτα σου.",

        // Categories
        cat_starters: "Ορεκτικά",
        cat_mains: "Κυρίως Πιάτα",
        cat_grills: "Από τη Σχάρα",
        cat_breads: "Ψωμιά",
        cat_desserts: "Επιδόρπια",
        cat_drinks: "Ποτά",

        // UI components
        add_btn: "ΠΡΟΣΘΗΚΗ",
        bestseller: "Δημοφιλές",

        // Items
        s1_name: "Μπρουσκέτα Αγορά",
        s1_desc: "Φρυγανισμένο προζύμι με ντομάτες ψημένες στη φωτιά, φρέσκο βασιλικό και παλαιωμένο βαλσάμικο",
        s2_name: "Γαρίδες Μυκόνου",
        s2_desc: "Γαρίδες jumbo μαριναρισμένες σε λεμόνι, σκόρδο και άγρια ρίγανη, ψημένες στα κάρβουνα",
        s3_name: "Ψητό Χαλούμι",
        s3_desc: "Κυπριακό κατσικίσιο τυρί ψημένο στη σχάρα με μέλι, θυμάρι και καβουρδισμένο σουσάμι",
        s4_name: "Καλαμάρι Ιονίου",
        s4_desc: "Ελαφρώς παναρισμένα δαχτυλίδια καλαμαριού με αλάτι λεμονιού-βοτάνων και αϊολί καπνιστής πάπρικας",
        m1_name: "Φακές Αιαίας",
        m1_desc: "Σιγομαγειρεμένες μαύρες φακές με αρωματικές ρίζες και φινίρισμα από έξτρα παρθένο ελαιόλαδο",
        m2_name: "Κοτόπουλο Λεμονάτο με Σκόρδο",
        m2_desc: "Ψητό κοτόπουλο σε βελούδινη σάλτσα λεμονιού-βουτύρου με κάπαρη και μεσογειακά βότανα",
        m3_name: "Αρνί με Κρούστα Βοτάνων",
        m3_desc: "Τρυφερό αρνάκι σιγομαγειρεμένο με δεντρολίβανο, θυμάρι και μια ιδέα μείωσης κόκκινου κρασιού",
        m4_name: "Νιόκι Σπανακιού Φλωρεντίας",
        m4_desc: "Απαλά νιόκι πατάτας με φρέσκο σπανάκι, ρικότα και βούτυρο φασκόμηλου",
        m5_name: "Λαβράκι Αδριατικής",
        m5_desc: "Σοταρισμένο λαβράκι με ψητά ντοματίνια, ελιές και ξύσμα λεμονιού",
        g1_name: "Ποικιλία Κρεατικών Ολύμπου",
        g1_desc: "Ένα μεγάλο πιάτο με παϊδάκια, κοτόπουλο με βότανα και μπιφτέκι με τζατζίκι",
        g2_name: "Μανιτάρια Πορτομπέλο στο Φούρνο",
        g2_desc: "Μεγάλα μανιτάρια γεμιστά με σκόρδο, βότανα και πεκορίνο, ψημένα σε ξυλόφουρνο",
        g3_name: "Σουβλάκια Αρνιού Σικελίας",
        g3_desc: "Μαριναρισμένα κομμάτια αρνιού με πιπεριές και κόκκινα κρεμμύδια, ψημένα στα κάρβουνα",
        b1_name: "Φοκάτσια με Βότανα",
        b1_desc: "Παραδοσιακό ιταλικό ψωμί με θαλασσινό αλάτι, δεντρολίβανο και ελαιόλαδο",
        b2_name: "Χειροποίητη Πίτα",
        b2_desc: "Μαλακή, ανοιγμένη στο χέρι ελληνική πίτα, ιδανική για ντιπ",
        b3_name: "Σκορδόψωμο Τοσκάνης",
        b3_desc: "Ζουμερές φέτες φρυγανισμένου ψωμιού τριμμένες με σκόρδο και βούτυρο",
        d1_name: "Μπακλαβάς με Μέλι Brûlée",
        d1_desc: "Κλασικό σιροπιαστό γλυκό με καρύδια και μέλι, με καραμελωμένη ζάχαρη στο πάνω μέρος",
        d2_name: "Τιραμισού Decadence",
        d2_desc: "Στρώσεις από σαβαγιάρ εμποτισμένα σε καφέ και χτυπημένο μασκαρπόνε με σκόνη κακάο",
        d3_name: "Πανακότα Σαφράν",
        d3_desc: "Μεταξένια ιταλική κρέμα με σαφράν και τριμμένο φιστίκι Αιγίνης",
        dr1_name: "Νέκταρ Αιγαίου",
        dr1_desc: "Αφρώδης χυμός σταφυλιού με νότες μελιού και κουφοξυλιάς",
        dr2_name: "Λεμονάδα με Δεντρολίβανο",
        dr2_desc: "Φρεσκοστυμμένο λεμόνι με ένα κλαδάκι δεντρολίβανο και σιρόπι αγαύης",
        dr3_name: "Εσπρέσο Αλεσμένος σε Πέτρα",
        dr3_desc: "Πλούσιος καφές σκούρου καβουρδίσματος, σερβίρεται με ένα κομμάτι μαύρη σοκολάτα",
    },

    it: {
        nav_home: "Home",
        nav_menu: "Menù",
        nav_story: "La Nostra Storia",
        nav_contact: "Contatti",
        nav_order: "Ordina",
        nav_est: "Est. MMXIX · Bengaluru",

        hero_badge: "✦  Autentica Cucina Mediterranea  ✦",
        hero_title: "DOVE I SAPORI ANTICHI",
        hero_subtitle: "vivono ancora",
        hero_desc: "Nata nelle cucine dell'Egeo e affinata sotto il sole del Mediterraneo — ogni piatto di Agora è un artefatto vivente di gusto, fuoco e tradizione.",
        hero_divider: "— ✦ —",
        hero_cta1: "Vedi il Menù",
        hero_cta2: "La Nostra Storia",
        hero_stat1: "Valutazione",
        hero_stat2: "Consegna",
        hero_stat3: "Ordine Min.",

        about_label: "La Nostra Storia",
        about_title1: "DALL'AGORA",
        about_title2: "alla tua tavola",
        about_p1: "Nell'antica Grecia, l'Agorà era molto più di un mercato — era il luogo dove idee, cultura e i frutti più pregiati della terra convergevano. Portiamo avanti quello spirito.",
        about_p2: "Lo Chef Nikos Papadopoulos si è formato ad Atene e a Napoli prima di portare le tradizioni culinarie del Mediterraneo a Bengaluru.",
        about_cta: "Esplora il Menù",
        about_img_tagline: "Servendo l'antica arte del fuoco",
        about_img_est: "Est. MMXIX",

        highlights_label: "La Via di Agorà",
        highlights_title: "Perché Gli Ospiti Tornano",
        highlights_subtitle: "Ogni dettaglio è intenzionale. Ogni ingrediente scelto. Ogni fiamma curata con dedizione.",

        best_label: "I Più Amati",
        best_title: "Scelti dall'Agorà",
        best_link: "Menù Completo",

        cta_eyebrow: "✦  BUON APPETITO  ✦",
        cta_title: "PRONTI A FESTEGGIARE?",
        cta_subtitle: "come gli dei un tempo",
        cta_desc: "Ordina dal nostro menù completo e ricevi il tuo pasto in 25–35 minuti. Consegna gratuita per ordini superiori a ₹499.",
        cta_btn: "Ordina Ora",

        menu_eyebrow: "Il Codice Culinario",
        menu_title: "IL NOSTRO MENÙ COMPLETO",
        menu_subtitle: "piatti, ognuno una storia forgiata dal fuoco e dalla tradizione",
        codex_all: "Tutti i Piatti",
        sidebar_title: "Il Codice",
        search_ph: "Cerca nel codice…",
        filter_veg: "Vegetariano",
        filter_best: "I Più Amati",
        no_dishes: "Nessun piatto trovato",
        no_dishes_sub: "Prova una ricerca diversa",
        view_order: "Vedi Ordine",

        cart_title: "Il Tuo Ordine",
        cart_from: "piatti da Agorà",
        cart_empty: "Il tuo carrello è vuoto",
        cart_empty_sub: "Aggiungi dei deliziosi piatti dal menù",
        cart_subtotal: "Subtotale",
        cart_delivery: "Spese di Consegna",
        cart_taxes: "Tasse (5%)",
        cart_total: "Totale",
        place_order: "Effettua Ordine",
        clear_cart: "Svuota carrello",
        order_placed: "Ordine Effettuato!",
        order_msg: "Il tuo cibo viene preparato con amore. Consegna stimata in 25–35 minuti.",

        footer_tagline: "Nata nell'Egeo, affinata nel Mediterraneo. Agorà porta l'antica arte del fuoco sulla tua tavola.",
        footer_nav: "Naviga",
        footer_menu_col: "Il Menù",
        footer_find: "Trovaci",
        footer_copy: "AGORÀ · BENGALURU · TUTTI I DIRITTI RISERVATI",
        footer_open: "11:00 – 23:30 ogni giorno",

        h1_title: "Maestria con il Fuoco",
        h1_desc: "Ogni piatto nasce dal fuoco aperto. I nostri chef padroneggiano l'arte antica del calore per estrarre sapori audaci e complessi.",
        h2_title: "Raccolto Mediterraneo",
        h2_desc: "Olio extravergine d'oliva, spezie macinate su pietra e cereali antichi provenienti direttamente da fattorie egee.",
        h3_title: "Eredità Culinaria",
        h3_desc: "Le nostre ricette risalgono a generazioni — storie viventi delle cucine greca, italiana e levantina.",
        h4_title: "30 Minuti o Meno",
        h4_desc: "Cibo caldo, confezionato magnificamente e consegnato direttamente alla tua porta.",

        // Categories
        cat_starters: "Antipasti",
        cat_mains: "Piatti Principali",
        cat_grills: "Dalla Griglia",
        cat_breads: "Pane",
        cat_desserts: "Dolci",
        cat_drinks: "Bevande",

        // UI components
        add_btn: "AGGIUNGI",
        bestseller: "Più Venduto",

        // Items
        s1_name: "Bruschetta Agora",
        s1_desc: "Pane a lievitazione naturale tostato con pomodori cotti al fuoco, basilico fresco e glassa di aceto balsamico invecchiato",
        s2_name: "Gamberi Mykonos",
        s2_desc: "Gamberoni marinati al limone, aglio e origano selvatico, cotti alla brace",
        s3_name: "Halloumi alla Griglia",
        s3_desc: "Formaggio caprino cipriota alla griglia con miele, timo e semi di sesamo tostati",
        s4_name: "Calamari dello Ionio",
        s4_desc: "Anelli di calamari leggermente impanati con sale al limone ed erbe, serviti con aioli alla paprika affumicata",
        m1_name: "Stufato di Lenticchie di Eea",
        m1_desc: "Lenticchie nere cotte a fuoco lento con radici aromatiche, completate da un filo di olio d'oliva spremuto a freddo",
        m2_name: "Pollo al Limone e Aglio",
        m2_desc: "Pollo arrosto in una vellutata salsa al burro e limone con capperi ed erbe mediterranee",
        m3_name: "Agnello in Crosta d'Erbe",
        m3_desc: "Tenero agnello cotto a fuoco lento con rosmarino, timo e una riduzione di vino rosso",
        m4_name: "Gnocchi alla Fiorentina con Spinaci",
        m4_desc: "Morbidi gnocchi di patate con spinaci freschi, ricotta e un filo di burro alla salvia",
        m5_name: "Branzino dell'Adriatico",
        m5_desc: "Branzino scottato in padella con pomodorini arrossiti, olive e scorza di limone",
        g1_name: "Grigliata Mista dell'Olimpo",
        g1_desc: "Un grande piatto di costolette d'agnello, pollo alle erbe e bifteki con tzatziki",
        g2_name: "Portobello al Forno",
        g2_desc: "Grandi funghi ripieni di aglio, erbe e pecorino, cotti nel forno a pietra",
        g3_name: "Spiedini d'Agnello alla Siciliana",
        g3_desc: "Cubetti di agnello marinati con peperoni e cipolle rosse, grigliati sulla brace",
        b1_name: "Focaccia alle Erbe",
        b1_desc: "Tradizionale focaccia italiana con sale marino, rosmarino e olio d'oliva",
        b2_name: "Pita Artigianale",
        b2_desc: "Morbida pita greca stesa a mano, perfetta per salse e hummus",
        b3_name: "Pane al Burro e Aglio Toscano",
        b3_desc: "Spesse fette di pane croccante sfregate con aglio e tostate con burro",
        d1_name: "Baklava al Miele Brûlée",
        d1_desc: "Classico dolce a strati con noci e miele, completato da una superficie di zucchero caramellato",
        d2_name: "Tiramisù Decadente",
        d2_desc: "Strati di savoiardi bagnati al caffè e mascarpone montato con spolverata di cacao amaro",
        d3_name: "Panna Cotta allo Zafferano",
        d3_desc: "Panna cotta setosa infusa allo zafferano e guarnita con granella di pistacchi",
        dr1_name: "Nettare dell'Egeo",
        dr1_desc: "Succo d'uva frizzante con sentori di miele e fiori di sambuco",
        dr2_name: "Limonata al Rosmarino",
        dr2_desc: "Limonata fresca con un rametto di rosmarino fresco e agave",
        dr3_name: "Espresso Macinato a Pietra",
        dr3_desc: "Caffè espresso ricco e scuro servito con un quadratino di cioccolato fondente",
    },

    hi: {
        nav_home: "होम",
        nav_menu: "मेनू",
        nav_story: "हमारी कहानी",
        nav_contact: "संपर्क",
        nav_order: "ऑर्डर",
        nav_est: "स्था. MMXIX · बेंगलुरु",

        hero_badge: "✦  प्रामाणिक भूमध्यसागरीय व्यंजन  ✦",
        hero_title: "जहाँ प्राचीन",
        hero_subtitle: "स्वाद जीवित रहते हैं",
        hero_desc: "एजियन की रसोई में जन्मी और भूमध्यसागरीय धूप में परिष्कृत — अगोरा की हर थाली स्वाद, अग्नि और परंपरा का जीता-जागता उदाहरण है।",
        hero_divider: "— ✦ —",
        hero_cta1: "मेनू देखें",
        hero_cta2: "हमारी कहानी",
        hero_stat1: "अतिथि रेटिंग",
        hero_stat2: "डिलीवरी",
        hero_stat3: "न्यूनतम ऑर्डर",

        about_label: "हमारी कहानी",
        about_title1: "अगोरा से",
        about_title2: "आपकी मेज़ तक",
        about_p1: "प्राचीन ग्रीस में, अगोरा महज़ एक बाज़ार से कहीं अधिक था — यह वह स्थान था जहाँ विचार, संस्कृति और धरती की सर्वोत्तम फसलें एकत्रित होती थीं। हम उसी भावना को आगे लेकर चलते हैं।",
        about_p2: "शेफ़ निकोस पापाडोपोलोस ने एथेंस और नेपल्स में प्रशिक्षण लिया और फिर भूमध्यसागरीय अग्नि-कला की परंपराओं को बेंगलुरु लाए।",
        about_cta: "हमारा मेनू देखें",
        about_img_tagline: "प्राचीन अग्नि-कला की सेवा में",
        about_img_est: "स्था. MMXIX",

        highlights_label: "अगोरा का तरीका",
        highlights_title: "अतिथि क्यों लौटते हैं",
        highlights_subtitle: "हर विवरण जानबूझकर है। हर सामग्री चुनी हुई। हर लौ प्रेम से सँजोई हुई।",

        best_label: "सबसे पसंदीदा",
        best_title: "अगोरा के चहेते व्यंजन",
        best_link: "पूरा मेनू",

        cta_eyebrow: "✦  बोन अपेतीत  ✦",
        cta_title: "भोज के लिए तैयार हैं?",
        cta_subtitle: "जैसे देवता कभी करते थे",
        cta_desc: "हमारे पूरे मेनू से ऑर्डर करें और 25–35 मिनट में अपना भोजन पाएँ। ₹499 से ऊपर के ऑर्डर पर मुफ्त डिलीवरी।",
        cta_btn: "अभी ऑर्डर करें",

        menu_eyebrow: "पाक-संहिता",
        menu_title: "हमारा पूरा मेनू",
        menu_subtitle: "व्यंजन, हर एक — आग और परंपरा की एक अनोखी कहानी",
        codex_all: "सभी व्यंजन",
        sidebar_title: "पाक-संहिता",
        search_ph: "संहिता में खोजें…",
        filter_veg: "शाकाहारी",
        filter_best: "पसंदीदा",
        no_dishes: "कोई व्यंजन नहीं मिला",
        no_dishes_sub: "एक अलग खोज आज़माएँ",
        view_order: "ऑर्डर देखें",

        cart_title: "आपकी ऑर्डर",
        cart_from: "व्यंजन अगोरा से",
        cart_empty: "आपकी कार्ट खाली है",
        cart_empty_sub: "मेनू से स्वादिष्ट व्यंजन जोड़ें",
        cart_subtotal: "कुल मूल्य",
        cart_delivery: "डिलीवरी शुल्क",
        cart_taxes: "कर (5%)",
        cart_total: "कुल",
        place_order: "ऑर्डर दें",
        clear_cart: "कार्ट साफ़ करें",
        order_placed: "ऑर्डर हो गया!",
        order_msg: "आपका खाना प्यार से तैयार किया जा रहा है। अनुमानित डिलीवरी: 25–35 मिनट।",

        // Footer
        footer_tagline: "एजियन में जन्मी, भूमध्यसागर में परिष्कृत। अगोरा प्राचीन अग्नि-कला को आपकी मेज़ तक लाती है।",
        footer_nav: "नेविगेट करें",
        footer_menu_col: "मेनू",
        footer_find: "हमें खोजें",
        footer_copy: "अगोरा · बेंगलुरु · सर्वाधिकार सुरक्षित",
        footer_open: "सुबह 11 – रात 11:30 बजे, रोज़ाना",

        h1_title: "अग्नि की महारत",
        h1_desc: "हर व्यंजन खुली लौ से जन्म लेता है। हमारे शेफ आग की प्राचीन कला में निपुण हैं।",
        h2_title: "भूमध्यसागरीय फसल",
        h2_desc: "ताज़ा निचोड़ा जैतून का तेल, पत्थर पर पिसे मसाले और एजियन के खेतों से सीधे लाए अनाज।",
        h3_title: "पाक परंपरा",
        h3_desc: "हमारी रेसिपी पीढ़ियों पुरानी हैं — ग्रीक, इतालवी रसोइयों की जीती-जागती कहानियाँ।",
        h4_title: "30 मिनट या उससे कम",
        h4_desc: "ताज़ा गर्म, खूबसूरत पैकेजिंग में सीधे आपके दरवाज़े तक।",

        // Categories
        cat_starters: "शुरुआती व्यंजन",
        cat_mains: "मुख्य भोजन",
        cat_grills: "तंदूर/ग्रिल से",
        cat_breads: "रोटियां",
        cat_desserts: "मीठा",
        cat_drinks: "पेय पदार्थ",

        // UI components
        add_btn: "जोड़ें",
        bestseller: "सबसे लोकप्रिय",

        // Items
        s1_name: "अगोरा ब्रुशेटा",
        s1_desc: "तंदूरी खट्टी रोटी (सॉअरडो) जिसपर भुने हुए टमाटर, ताज़ा तुलसी और पुराना सिरका छिड़का हुआ",
        s2_name: "मायकोनोस प्रॉन्स",
        s2_desc: "नींबू, लहसुन और जंगली अजवायन में मसालेदार जंबो झींगे, कोयले पर भुने हुए",
        s3_name: "ग्रिल्ड हलौमी",
        s3_desc: "शहद, अजवायन के फूल और भुने हुए तिल के साथ ग्रिल किया हुआ साइप्रस का बकरी का पनीर",
        s4_name: "आयनियन कैलामारी",
        s4_desc: "नींबू-जड़ी बूटी नमक और स्मोक्ड लाल मिर्च के साथ तले हुए स्क्विड के छल्ले",
        m1_name: "ऐअन मसूर स्ट्यू",
        m1_desc: "धीमी आंच पर पकी हुई काली दाल, सुगंधित कंदों और ठंडी विधि से निकाले गए जैतून के तेल के साथ",
        m2_name: "लेमन गार्लिक पोलो",
        m2_desc: "केपर्स और भूमध्यसागरीय जड़ी बूटियों के साथ मखमली नींबू-मक्खन सॉस में भुना हुआ चिकन",
        m3_name: "हर्ब-क्रस्टेड मेमना",
        m3_desc: "दौना (रोज़मेरी), अजवायन के फूल और रेड वाइन के साथ पकाया गया कोमल मेमने का मांस",
        m4_name: "फ्लोरेंस पालक न्योकी",
        m4_desc: "ताजा पालक, रिकोटा पनीर और सेज बटर के साथ नरम आलू के न्योकी",
        m5_name: "एड्रियाटिक सी बास",
        m5_desc: "भुने हुए चेरी टमाटर, जैतून और नींबू के छिलके के साथ तवा-तली सी बास मछली",
        g1_name: "ओलंपियन मिक्स्ड ग्रिल",
        g1_desc: "मेमने के चॉप्स, हर्ब चिकन और त्ज़त्ज़िकी के साथ बिफ़्तेकी की एक बड़ी थाली",
        g2_name: "पोर्टोबेलो अल फोर्नो",
        g2_desc: "लहसुन, जड़ी बूटियों और पेकोरिनो पनीर से भरे हुए बड़े मशरूम, जिन्हें पत्थर के तंदूर में भूना गया है",
        g3_name: "सिसिली लैम्ब स्क्यूवर्स",
        g3_desc: "शिमला मिर्च और लाल प्याज के साथ मसालेदार मेमने के टुकड़े, कोयले पर ग्रिल किए हुए",
        b1_name: "हर्ब फोकाचा",
        b1_desc: "समुद्री नमक, दौना (रोज़मेरी) और जैतून के तेल के साथ पारंपरिक इतालवी रोटी",
        b2_name: "पीटा आर्टिजाना",
        b2_desc: "मुलायम, हाथ से बेली हुई ग्रीक पीटा ब्रेड, जो सॉस/दही के साथ खाने के लिए उत्तम है",
        b3_name: "टस्कन गार्लिक ब्रेड",
        b3_desc: "मक्खन के साथ टोस्ट की गई और लहसुन लगी हुई कुरकुरी ब्रेड के मोटे टुकड़े",
        d1_name: "हनी बकलावा ब्रूली",
        d1_desc: "अखरोट और शहद के साथ बनी क्लासिक परतों वाली मिठाई, जिसके ऊपर कैरामेलाइज़्ड चीनी की परत है",
        d2_name: "तिरामिसू डेकाडेंस",
        d2_desc: "कॉफी में भीगे हुए लेडीफिंगर्स बिस्कुट और डार्क कोको डस्ट के साथ व्हीप्ड मस्कारपोन पनीर की परतें",
        d3_name: "केसर पन्ना कोट्टा",
        d3_desc: "केसर के स्वाद वाला रेशमी इतालवी क्रीम डेज़र्ट, जिसके ऊपर कुचले हुए पिस्ते हैं",
        dr1_name: "एजियन नेक्टर",
        dr1_desc: "शहद और एल्डरफ्लावर के स्वाद के साथ चमकीला अंगूर का रस",
        dr2_name: "रोज़मेरी लेमोनेड",
        dr2_desc: "ताजा निचोड़ा हुआ नींबू जिसमें बगीचे की रोज़मेरी की टहनी और हल्का एगेव रस है",
        dr3_name: "स्टोन-ग्राउंड एस्प्रेसो",
        dr3_desc: "गहरे रंग की भुनी हुई कड़क कॉफी जिसे डार्क चॉकलेट के एक छोटे टुकड़े के साथ परोसा जाता है",
    },
};interface LanguageContextType {
    lang: Language;
    setLang: (l: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [lang, setLang] = useState<Language>("en");
    const t = (key: string) => translations[lang][key] ?? translations["en"][key] ?? key;
    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLang() {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error("useLang must be used within LanguageProvider");
    return ctx;
}
